PUT http://localhost:8080/users/11111111-1111-1111-1111-111111111111
Content-Type: application/json

{
    "id" : "2",
    "firstName" : "Alex",
    "lastName" : "Shch",
    "profileName" : "serius",
    "signDate" : "06/06/2024",
    "email" : "serius@gmail.com",
    "password" : "password"
}