# server:
#   port: 
#     8080


# spring:
#   datasource:
#     driver-class-name: org.postgresql.Driver
#     url: jdbc:postgresql://localhost:5432/Prostogram
#     username: postgres
#     password: Main1!
#   jpa:
#     database:   POSTGRESQL
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#   flyway:
#     baseline-on-migrate: true